blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from blog import views


urlpatterns = [
	url(r'^$', views.post_list),
    url(r'^page/(?P<page_num>[\w\d+]+)/$', views.post_list, name='page'),
    url(r'^tagged/(?P<tag_name>[-\w\d]+)/$', views.tagged_post_list, name='view_tagged_posts'),
    url(r'^tagged/(?P<tag_name>[-\w\d]+)/page/(?P<page_num>[\w\d]+)/$', views.tagged_post_list, name='view_tagged_posts'),
    url(r'^author/(?P<username>[-\w\d]+)/page/(?P<page_num>[\w\d]+)/$', views.posts_by_author, name='view_posts_by_author'),
    url(r'^author/(?P<username>[-\w\d]+)/$', views.posts_by_author, name='view_posts_by_author'),
    url(r'^edit_post/(?P<pk>[\w\-]+)/(?P<slug>[\w\d-]+)?/?$', views.edit_post, name='edit_post'),
    url(r'^add_post/$', views.add_post, name='add_post'),
    url(r'^delete_post/(?P<pk>[\d+]+)/(?P<slug>[\w\d-]+)?/?$', views.delete_post, name='delete_post'),
    url(r'^delete_comment/(?P<pk>[\d+]+)/$', views.delete_comment, name='delete_comment'),
    url(r'^comment/(?P<pk>[\w+\d+]+)/(?P<slug>[\w\d-]+)?/?$', views.add_comment, name='add_comment'),
    url(r'^post/(?P<pk>[\w\d]+)/(?P<slug>[\w\d-]+)?/?$', views.single_post_view, name='single_post_view'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^upload/$', views.upload_handler),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/(?P<query_string>[\w\d\W]+)/page/(?P<page_num>[\w\d]+)/$', views.search, name='search'),
]

technarium/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
#from django.contrib import flatpages
from blog import views

urlpatterns = [
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^main\.html', views.redirector),
    url(r'^join\.html', views.redirector),
    url(r'^projects\.html', views.redirector),
    url(r'^friends\.html', views.redirector),
    url(r'^support\.html', views.redirector),
    url(r'^equipment\.html', views.redirector),
    url(r'^index\.html', views.redirector),
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)[0],
    url(r'', include('django.contrib.flatpages.urls')),
] 

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Tag(models.Model):
	name = models.CharField(max_length=128, unique=True)

	def __str__(self):
		return self.name

class Comment(models.Model):
	posted_by = models.CharField(max_length=128, null=True)
	body = models.TextField()
	date_time = models.DateTimeField()
	post = models.ForeignKey('Post')

	def __str__(self):
		return self.body

class Post(models.Model):
	title = models.CharField(max_length=128, default='No title', null=True, blank=True)
	body = models.TextField()
	slug = models.SlugField()
	date_time = models.DateTimeField()
	timestamp = models.IntegerField()
	tags = models.ManyToManyField(Tag,blank=True)
	created_by = models.ForeignKey('UserProfile', null=True)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.title)
		super(Post, self).save(*args, **kwargs)

	class Meta:
		ordering = ['-date_time']

	def __str__(self):
		return self.slug

class UserProfile(models.Model):
	user = models.OneToOneField(User) # required

	def __str__(self):
		return self.user.username

blog/forms.py
import re
from django import forms
from django.utils.text import slugify
from blog.models import Post, Tag, Comment

class PostForm(forms.ModelForm):
	title = forms.CharField()
	body = forms.CharField(widget=forms.Textarea)
	date_time = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M:%S'], widget=forms.HiddenInput)
	tags = forms.CharField(min_length=1,required=False)
	timestamp = forms.IntegerField(widget=forms.HiddenInput)

	def clean(self):
		cleaned_data = self.cleaned_data
		tags = cleaned_data.get('tags')
		if tags:
			if re.search(r"[^-\w, ]",tags):
				self.add_error('tags', 'Invalid character(s) in tags, only alphanumeric chars and - allowed')
		return cleaned_data

	class Meta:
		model = Post
		fields = ['title', 'body','date_time','timestamp']


class CommentForm(forms.ModelForm):
	posted_by = forms.CharField()
	body = forms.CharField(widget=forms.Textarea)
	date_time = forms.DateTimeField(widget=forms.HiddenInput)

	class Meta:
		model = Comment
		fields = ['body', 'date_time', 'posted_by']

class DeletePost(forms.ModelForm):
	class Meta:
		model = Post
		fields = []

class DeleteComment(forms.ModelForm):
	class Meta:
		model = Comment
		fields = []

class SearchForm(forms.Form):
	search= forms.CharField(label="Search...", max_length=256)

blog/views.py
import re
import time
import urllib.parse
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from blog.models import Post, Tag, Comment, UserProfile
from blog.forms import PostForm, CommentForm, DeletePost
from blog.utils import write_file, get_query


def redirector(request):
	'''redirects old urls to new ones. /join.html/?language=lt >> /join/en/'''

	if 'language' in request.GET:
		lang = request.GET['language']
	else:
		lang = 'en'
	url = request.get_full_path() # >> '/index.html'
	url = re.split(r'\.', url)[0] # >> '/index'
	if url =='/main': # main page doesn't follow /resource/language/ convention so we process it separately
		if lang == 'en': 
			return HttpResponseRedirect('/')
		else:
			return HttpResponseRedirect('/lt')
	else:
		url = url + '/' + lang 	
		return HttpResponseRedirect(url)


@login_required
@csrf_exempt
def upload_handler(request):
	if request.method == 'POST':
		filename = str(request.FILES['file'])
		write_file(filename, request.FILES['file'])
		return HttpResponse('{ "location" :'+ '"/media/usr/'+filename+'"}')

def search(request, query_string=None, page_num=1):
	page_num=int(page_num)
	if query_string == None:
		''' this is for the first page of the result where query is passed trough 
		the request's payload instead of the url''' 
		if ('q' in request.GET) and request.GET['q'].strip():
			query_string = request.GET['q']  			
			entry_query = get_query(query_string, ['title', 'body','tags__name'])     
			found_entries = Post.objects.filter(entry_query).order_by('-date_time').distinct()[page_num*10-10:page_num*10]
			context_dict = {'query_string': query_string, 'post_list': found_entries }
	else:
		query_string = urllib.parse.unquote_plus(query_string)
		entry_query = get_query(query_string, ['title', 'body','tags__name'])     
		found_entries = Post.objects.filter(entry_query).order_by('-date_time').distinct()[page_num*10-10:page_num*10]
		context_dict = {'query_string': query_string, 'post_list': found_entries }


	if page_num == 1: #render full page if we're on the first pageq
		return render(request, 'blog/post_list.html', context_dict)
	else: # else render only the post_list without header, etc
		return render(request, 'blog/post_list_template.html', context_dict) 

def post_list(request, page_num=1):
	page_num=int(page_num)
	post_list = Post.objects.all().order_by('-date_time')[page_num*10-10:page_num*10] # query next 10 posts
	tag_list = Tag.objects.all()
	context_dict={'post_list': post_list, 'page_num': page_num}
	if page_num == 1: #render full page if we're on the first page
		return render(request, 'blog/post_list.html', context_dict)
	else: # else render only the post_list without header, etc
		return render(request, 'blog/post_list_template.html', context_dict) 

def single_post_view(request, pk, slug=None): 
	# slug is only for eye candy in the url, we get posts by primary key (pk)
	post = Post.objects.get(pk=pk)
	context_dict={'post':post}
	return render(request, 'blog/single_post_view.html', context_dict)

def tagged_post_list(request, tag_name, page_num=1):
	page_num=int(page_num)
	tag = Tag.objects.get(name=tag_name)
	tagged_post_list = tag.post_set.all().order_by('-date_time')[page_num*10-10:page_num*10] # query next 10 tagged posts
	context_dict = {'post_list':tagged_post_list, 'page_num': page_num, 'current_tag':tag_name}
	if page_num == 1: #render full page if we're on the first page
		return render(request, 'blog/post_list.html', context_dict)
	else: # else render only the post_list without header, etc
		return render(request, 'blog/post_list_template.html', context_dict)

def posts_by_author(request, username, page_num=1):
	page_num = int(page_num)
	user = User.objects.get(username = username)
	user = UserProfile.objects.get(user = user)
	post_list = user.post_set.all().order_by('-date_time')[page_num*10-10:page_num*10] # query next 10 tagged posts
	context_dict = {'post_list': post_list, 'page_num':page_num}
	if page_num == 1: #render full page if we're on the first page
		return render(request, 'blog/post_list.html', context_dict)
	else: # else render only the post_list without header, etc
		return render(request, 'blog/post_list_template.html', context_dict)

@login_required(login_url="/login/")
def edit_post(request, pk,slug=None):
	post = Post.objects.get(pk=pk)
	user = UserProfile.objects.get(user=request.user)


	if not request.user.is_superuser: # if not admin and not post creator return 403
		if user != post.created_by:
			return HttpResponseForbidden()

	if request.method == 'POST':
		form = PostForm(request.POST, instance=post) #overwrite the db entry for the Post instance
		if form.is_valid():
			# tags are processed separately, the field for the post instance is cleared and the new tags are added to it.

			post.tags.all().delete()
			tag_list = form.cleaned_data['tags'].split(',')
			tag_list = [tag.rstrip() for tag in tag_list if tag != ' ' and tag != ''] # clean 
			#tag_list = map(lambda tag: re.sub(r' ', r'-', tag.lower()), tag_list) #clean
			for tag in tag_list:
				tag, created=Tag.objects.get_or_create(name=slugify(tag)) 
				post.tags.add(tag)
						
			form.save()
			return HttpResponseRedirect(reverse('single_post_view', kwargs={'pk':pk, 'slug':slug}))
		else:
			return render(request, 'blog/edit_post.html', {'form':form})

	else:
		# unbound form - send all the tags to be prefilled as a str to the tags field in the form - 'tag, tag2,'
		tags=str(post.tags.all())
		tags=re.findall(r'[-_\w+]+', tags)
		tags=[tag+',' for tag in tags if tag != 'Tag'] # can't remember why !='Tag'
		tags = ' '.join(tags)
		form=PostForm(initial={'body':post.body.encode('UTF-8'), 
								'title':post.title,
								'date_time':post.date_time,
								'tags':tags,
								'timestamp':int(time.time()),
								})

		return render(request, 'blog/edit_post.html', {'form':form})

@login_required(login_url="/login/")
def delete_post(request, pk,slug=None):
	
	post=get_object_or_404(Post, pk=pk)
	

	user = UserProfile.objects.get(user=request.user)
	if not request.user.is_superuser: # if not admin and not post creator return 403
		if user != post.created_by:
			return HttpResponseForbidden()

	if request.method == "POST":
		form = DeletePost(request.POST, instance=post)
		if form.is_valid():
			post.delete()
			return HttpResponseRedirect('/blog/')
	else:
		form = DeletePost(instance=post)
		return render(request,'blog/delete_object.html', {'form':form, 'post':post})

@user_passes_test(lambda u: u.is_superuser)
def delete_comment(request, pk):
	if not request.user.is_superuser: #only admin can delete comments for now
		return HttpResponseForbidden()

	comment=get_object_or_404(Comment, pk=pk)
	if request.method == "POST":
		form = DeletePost(request.POST, instance=comment)
		if form.is_valid():
			comment.delete()
			return HttpResponseRedirect(reverse('single_post_view', kwargs={'pk':comment.post.pk}))
	else:
		form = DeletePost(instance=comment)
		return render(request,'blog/delete_object.html', {'form':form, 'comment':comment})

@login_required(login_url="/login/")
def add_post(request):
	
	if request.method == 'POST':
		form = PostForm(request.POST)
		user = UserProfile.objects.get(user=request.user)
		if form.is_valid():
			tag_list = form.cleaned_data['tags'].split(',')
			tag_list = [tag.rstrip() for tag in tag_list if tag != ' ' and tag != ''] # clean 

			obj = form.save()
			obj.slug=slugify(request.POST['title'])
			obj.created_by = user
			for tag in tag_list:
				tag, created=Tag.objects.get_or_create(name=slugify(tag))
				obj.tags.add(tag)
			obj.save()
			return HttpResponseRedirect(reverse('single_post_view', kwargs={'pk':obj.pk, 'slug':obj.slug}))
	else:
		form = PostForm(initial={'timestamp':int(time.time()),
								'date_time': time.strftime('%Y-%m-%d %H:%M:%S',time.localtime())})

	return render(request, 'blog/add_post.html', {'form':form})

def add_comment(request, pk, slug=None):
	post = Post.objects.get(pk=pk)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			obj=form.save(commit=False)
			obj.post_id=pk
			form.save()
			return HttpResponseRedirect(reverse('single_post_view', kwargs={'pk':pk, 'slug':slug}))
	else:
		form = CommentForm(initial={'date_time': time.strftime('%Y-%m-%d %H:%M:%S',time.localtime())})
	return render(request, 'blog/add_comment.html', {'form':form, 'post':post})

def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request, user)
				return redirect('/blog/')
			else:
				return HttpResponse('Account is disabled')
		else:
			return HttpResponse('Username or password is incorrect')
	else:
		return render(request, 'blog/login.html', {})

@login_required(login_url="/login/")
def user_logout(request):
	logout(request)
	return redirect('/blog/')

blog/templates/blog/add_comment.html
{% extends "blog/main.html" %}
{% block head %}
{% load static %}
<title> {{post.title}} </title>
<link rel="stylesheet" type="text/css" href="{% static 'blog/single_post.css' %}">
{% endblock %}
{% block content %}
	<div class='post'>
		<h1 class='post_title'>{{post.title}}</h1>
		<div class='post_body'><p>{{ post.body|safe }}</p></div>
		<div class='post_date'>Posted on {{post.date_time}}</div>
		<div class='tags'>Tagged</br>
			{% for tag in post.tags.all %}
			<a class='btn tag_button' href="{% url 'view_tagged_posts' tag_name=tag.name %}">{{tag.name}}</a>
			{% endfor %}
		</div>
		<div class='comments'>
			{% for comment in post.comment_set.all %}
			<div class='comment'>
				<div id='comment_header'>Posted at: {{ comment.date_time }} by {{ comment.posted_by }}</br></div>
				{{ comment.body }}
				{% if user.is_superuser %}
				<a id='delete_comment_btn' href="{% url 'delete_comment' comment.pk %}">Delete Comment</a>
				{% endif %}
			</div>
			{% endfor %}
				<div id='comment_form'>
	<form class='post_form' method="POST" action="">
	{% csrf_token %}
	<div id='comment_posted_by'>Name:{{form.posted_by}}</div>
	<div id='comment_body'>{{form.body}}</div>
	{{form.date_time}}
	{{form.errors}}
	<input type='submit' name='submit' value='Submit comment'/>
	</form>
	</div>
		</div>
{% endblock %}

blog/templates/blog/add_post.html
{% extends "blog/main.html" %}
{% block head %}
{% load static %}
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script src="{% static 'blog/tag_editor/jquery.caret.min.js' %}"></script>
<script src="{% static 'blog/tag_editor/jquery.tag-editor.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'blog/tag_editor/jquery.tag-editor.css' %}">
<title>Adding a new post</title>
{% endblock %}
{% block content %}
	<h1>Adding a new post</h1>
	<form id='post_form' method="POST" action="">
		{% csrf_token %}
		<div id='post_title_form'>Title:{{ form.title }}</div>
		<div id='post_body_form'>{{ form.body }}</div>
		{{ form.date_time }}
		{{ form.timestamp }}
		<div id='post_tags_form'>Tags:{{ form.tags }}</div>
		{{ form.slug }}
		{{ form.errors }}
		<input id='submit_btn' type='submit' name='submit' value='Sumbit Post'/>
	</form>

 <script type="text/javascript">
  tinymce.init({ 
   selector:'#id_body',
   plugins: [
    'advlist autolink autosave autoresize lists link image charmap preview hr anchor pagebreak',
    'searchreplace code fullscreen',
    'insertdatetime media nonbreaking save table contextmenu directionality',
    'paste textcolor colorpicker textpattern codesample toc'
  ],
  toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link ',
  toolbar2: ' image media | forecolor backcolor emoticons | codesample | code preview',
  media_poster: false,
   image_title: true, 
  images_upload_url: '/blog/upload/',
  images_upload_base_path: '/',
  file_picker_types: 'image', 
  relative_urls : false,
  file_picker_callback: function(cb, value, meta) {
    var input = document.createElement('input');
    input.setAttribute('type', 'file');
    input.setAttribute('accept', 'image/*');
    input.onchange = function() {
      var file = this.files[0];
      var id = 'blobid' + (new Date()).getTime();
      var blobCache = tinymce.activeEditor.editorUpload.blobCache;
      var blobInfo = blobCache.create(id, file);
      blobCache.add(blobInfo);
      cb(blobInfo.blobUri(), { title: file.name });
    };
    
    input.click();
  },
   width:700,
   height: 500 });

            $('#id_tags').tagEditor({
                placeholder: 'Enter tags ...',})
</script>
{% endblock %}

blog/templates/blog/delete_object.html
{% extends "blog/main.html" %}
{% block content %}
{% if post %}
Delete {{post.title}} ?
{% endif %}
{% if comment %}
Delete the comment {{ comment.body }}?
{% endif %}
<form method='post' action=''>
		{% csrf_token %}
		<button type="submit" class="btn">Yes</button>
</form>
{% endblock %}

blog/templates/blog/edit_post.html
{% extends "blog/main.html" %}
	{% block head %}
	{% load static %}
  	<script src="{% static 'blog/tinymce/tinymce.min.js' %}"></script>
  	<script src="{% static 'blog/tag_editor/jquery.caret.min.js' %}"></script>
  	<script src="{% static 'blog/tag_editor/jquery.tag-editor.min.js' %}"></script>
  	<link rel="stylesheet" type="text/css" href="{% static 'blog/tag_editor/jquery.tag-editor.css' %}">
  	<title> Editing a post</title>
  	{% endblock %}
	{% block content %}
	<h1>Editing a post</h1>
	<form id='post_form' method="POST" action="">
		{% csrf_token %}
		<div id='post_title_form'>Title:{{ form.title }}</div>
		<div id='post_body_form'>{{ form.body }}</div>
		{{ form.date_time }}
		{{ form.timestamp }}
		<div id='post_tags_form'>Tags:{{ form.tags }}</div>
		{{ form.slug }}
		{{ form.errors }}
		<input id='submit_btn' type='submit' name='submit' value='Edit Post'/>
	</form>
 <script type="text/javascript">
  tinymce.init({ 
   selector:'#id_body',
   plugins: [
    'advlist autolink autosave autoresize lists link image charmap preview hr anchor pagebreak',
    'searchreplace code fullscreen',
    'insertdatetime media nonbreaking save table contextmenu directionality',
    'paste textcolor colorpicker textpattern codesample toc'
  ],
  toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link ',
  toolbar2: ' image media | forecolor backcolor emoticons | codesample | code preview',
  media_poster: false,
   image_title: true, 
  images_upload_url: '/blog/upload/',
  images_upload_base_path: '/',
  file_picker_types: 'image', 
  relative_urls : false,
  file_picker_callback: function(cb, value, meta) {
    var input = document.createElement('input');
    input.setAttribute('type', 'file');
    input.setAttribute('accept', 'image/*');
    input.onchange = function() {
      var file = this.files[0];
      var id = 'blobid' + (new Date()).getTime();
      var blobCache = tinymce.activeEditor.editorUpload.blobCache;
      var blobInfo = blobCache.create(id, file);
      blobCache.add(blobInfo);
      cb(blobInfo.blobUri(), { title: file.name });
    };
    
    input.click();
  },
   width:700,
   height: 500 });

            $('#id_tags').tagEditor({
                placeholder: 'Enter tags ...',})
</script>
	{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/main.html'%}
{% load static %}

{% block content %}
<h1>Login</h1>
<form id='login_form' method='post' action=''>
	{% csrf_token %}
	Username: <input type ='text' name='username' value=''/>
	<br />
	Password: <input type = 'password' name='password' value=''/>
	<br />
	<input type='submit' value='submit'/>
</form>
{% endblock %}

blog/templates/blog/main.html
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	{% load static %}
	{% block head %}
	{% endblock %}
	<link rel="stylesheet" type="text/css" href="{% static 'blog/fonts.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'blog/blog.css' %}">
	
	
</head>
<body>
	<div id="container">
	<div id="search">
		<form method="get" action="/blog/search/">
		<label for="id_q">Search:</label>
		           <input type="text" name="q" id="id_q"/>
		           <input type="submit" value="Submit"/>
		        </form>
		 
	</div>
	<div id='login_panel'>
	{% if user.is_authenticated %}
		Logged in as {{user.username}}<a class='btn' id='logout_btn' href="{% url 'logout' %}">Logout</a>
		<a class='btn' id='add_post_btn'href="{% url 'add_post' %}">Add a new Post </a>
	{% else %}
		<a class='btn' id='login_btn' href="{% url 'login' %}">Login</a>
	{% endif %}
	</div>
	<div id='sidebar'>
	
		<div id="blog_logo">
	<a href="/"><img src='{{MEDIA_URL}}blog/logo_small.png'/></a>
	</div>
	<div id="description">
		A hackerspace in Vilnius, Lithuania. All content CC BY-NC-SA 4.0.
	</div>	
		<div id="nav">
	<p><a id = 'joinLink' href="/join/en/" title="Join us!"><img src="{{MEDIA_URL}}blog/she-wolf.png" alt="Join us!"/>Join Technarium!</a></p>
	<p><a href="/projects/en/" title="Our projects and ideas"><img src="{{MEDIA_URL}}blog/feynman_diagram.png" />Projects &amp; ideas</a></p>
	<p><a href="/equipment/en/" title="Tools and equipment"><img src="{{MEDIA_URL}}blog/tools.png" />Tools &amp; equipment</a></p>
	<p><a href="/friends/en/" title="Our friends"><img src="{{MEDIA_URL}}blog/mandelbrot.png" />Friends</a></p>
	<p><a href="/support/en/" title="Support us!"><img src="{{MEDIA_URL}}blog/battery.png" />Support us!</a></p>
		</div>
	</div>
		<div id='post_list'>
		{% block post_list %}
		{% endblock %}
		{% block content %}
		{% endblock %}
	</div>
	</div>
</body>
</html>

blog/templates/blog/post_list.html
{% extends "blog/main.html" %}
{% block head %}
{% load staticfiles%}
	<script src="{% static 'blog/infinite_scroll.js' %}"></script>
		<title>Technarium blog</title>
{% endblock %}
{% block post_list %}
	{% include "blog/post_list_template.html" %}
{% endblock %}

blog/templates/blog/post_list_template.html
{% if post_list %}
	{% for post in post_list %}
		<div class='post'>
		<h1 class='post_title'>
		<a href="{% url 'single_post_view' slug=post.slug pk=post.pk %}">{{post.title}}</a>
		</h1>
		<div class='post_body'><p>{{ post.body|safe }}</p></div>
		<div class='post_date'>Posted on <a class="posted_date" href="{% url 'single_post_view' slug=post.slug pk=post.pk %}">{{post.date_time}}</a>
		{% if post.created_by %}
		by <a href="{% url 'view_posts_by_author' username=post.created_by %}">{{ post.created_by }}</a>
		{% endif %}
		</div>
		<div class='tags'>Tagged</br>
			{% for tag in post.tags.all %}
			<a class='btn tag_button' href="{% url 'view_tagged_posts' tag_name=tag.name %}">{{tag.name}}</a>
			{% endfor %}
		</div>
		{% if user.is_authenticated %}
			{% if user.username == post.created_by.user.username or user.is_superuser %}
			<a href="{% url 'edit_post' pk=post.pk slug=post.slug %}">Edit post</a>
			<a href="{% url 'delete_post' pk=post.pk slug=post.slug %}">Delete post</a>
			{% endif %}
		{% endif %}
		{% if post.comment_set.count > 0 %}
			<a href="{% url 'add_comment' pk=post.pk slug=post.slug  %}">
			{{post.comment_set.count}} Comments
			</a>
			{% else %}
			<a href="{% url 'add_comment' pk=post.pk slug=post.slug  %}">Add a comment</a>
		{% endif %}
	</div>
	{% endfor %}
{% endif %}

blog/templates/blog/single_post_view.html
{% extends "blog/main.html" %}
{% block head %}
{% load static %}
<title> {{post.title}} </title>
	<link rel="stylesheet" type="text/css" href="{% static 'blog/fonts.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/single_post.css' %}">
{% endblock %}
{% block content %}
	<div class='post'>
		<h1 class='post_title'>{{post.title}}</h1>
		<div class='post_body'><p>{{ post.body|safe }}</p></div>
		<div class='post_date'>Posted on {{post.date_time}}
		{% if post.created_by %}
		by <a href="{% url 'view_posts_by_author' username=post.created_by %}">{{ post.created_by }}</a>
		{% endif %}
		</div>
		<div class='tags'>Tagged</br>
			{% for tag in post.tags.all %}
			<a class='btn tag_button' href="{% url 'view_tagged_posts' tag_name=tag.name %}">{{tag.name}}</a>
			{% endfor %}
		</div>
		<div class='comments'>
			{% for comment in post.comment_set.all %}
			<div class='comment'>
				<div id='comment_header'>Posted at: {{ comment.date_time }} by {{ comment.posted_by }}</br></div>
				{{ comment.body }}
				{% if user.is_superuser %}
				<a href="{% url 'delete_comment' comment.pk %}">Delete Comment</a>
				{% endif %}
			</div>
			{% endfor %}
		</div>
		{% if user.is_authenticated %}
			{% if user.username == post.created_by.user.username or user.is_superuser %}
		<a href="{% url 'edit_post' pk=post.pk slug=post.slug %}">Edit post</a>
		<a href="{% url 'delete_post' pk=post.pk slug=post.slug %}">Delete post</a>
			{% endif %}
		{% endif %}
		<a href="{% url 'add_comment' pk=post.pk slug=post.slug %}">Add a comment</a>
	</div>
{% endblock %}